config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index         # GET /restaurants
    @tasks = Task.all
  end

  def show          # GET /restaurants/:id
  end

  def new           # GET /restaurants/new
    @task = Task.new
  end

  def create        # POST /restaurants
    @task = Task.new(task_params)
    @task.save

    redirect_to root_path
  end

  def edit          # GET /restaurants/:id/edit
  end

  def update        # PATCH /restaurants/:id
    @task.update(task_params)

    redirect_to root_path
  end

  def destroy       # DELETE /restaurants/:id
    @task.destroy

    redirect_to root_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:name, :content, :status)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :status %>
  <%= f.check_box :status %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>TASKS LIST</h1>
<% @tasks.each do |task| %>
  <%= task.id %> : <%= task.name %><p></p>
  <%= link_to "Show", task_path(task) %>
  <%= link_to "Edit", edit_task_path(task) %>
  <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  <hr>
<% end %><p></p>
<h2><%= link_to "Add a new task", new_task_path %></h2>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<!-- Should display the task's details (content, date of creation, etc.) and a back-link to the index page. -->

<h2>  <%= @task.id%> : <%= @task.name %> </h2>
<p> Description : <%= @task.content %> </p>
<p>Status: <strong><%= @task.status %></strong></p>

<%= link_to "Home page", tasks_path %>